registry:
    command: -server -bootstrap -ui-dir /ui
    image: progrium/consul:latest
    hostname: registry
    ports:
        - "8300:8300"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
micro:
    command: --registry_address=registry:8500 api
    image: microhq/micro:latest
    links:
        - registry
    ports:
        - "8080:8080"
web:
    command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
    image: microhq/micro:latest
    links:
      - registry
    ports:
    - "8082:8082"
joke:
    image: radekdymacz/joke-srv:latest
    command: --registry_address=registry:8500
    links:
        - registry
name:
    image: radekdymacz/name-srv:latest
    command: --registry_address=registry:8500
    links:
        - registry
api:
    image: radekdymacz/api-srv:latest
    command: --registry_address=registry:8500
    links:
        - registry   